version: 2

updates:
- package-ecosystem: "docker-compose"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  cooldown:
    - default-days: 30
    - semver-major-days: 30
    - semver-minor-days: 14
    - semver-patch-days: 7
